### ISSUE TITLE
Fails to install: missing Devel::Hide

### ISSUE THREAD

**Issue by felliott** [plicease-legacy/Dist-Zilla-PluginBundle-Author-Plicease#6]
Hello,

This module is failing to install for me, because `t/unbundle.t` runs `example/unbundle.pl` which requires `Devel::Hide`, which is not installed.  I don't speak fluent `dzil`, but I think it's listed as a develop prereq rather than a hard prereq in the `dist.ini`.

Also, I think I used too many or not enough commas in that first sentence, but that's on me. :)

Cheers,
Fitz

**Comment by plicease** [comment]
Thanks for pointing this out.  I made it skip the test if `Devel::Hide` is not installed.  I think I can make it be a true dev only dep by moving the usage to inc/run/before_build.pl.  I think that would be better.

**Comment by plicease** [comment]
I believe this should be fixed in 1.75.

**Comment by plicease** [comment]
It may not appear fixed until 1.77 because of another bug that I introduced.
